version: '3'
services:
  siot:
    container_name: flask
    volumes:
      - ./src:/root/src
    build:
      context: ./src
      dockerfile: ./Dockerfile
    ports:
      - 5678:5000
    depends_on:
      - mysql
#    links:
#      - mysql
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD : 123456
      MYSQL_DATABASE : siot
      TZ: Asia/Shanghai
    ports:
      - 1306:3306